### ISSUE TITLE
$ is not defined

### ISSUE THREAD

**Issue by gauripadbidri** [Iperity/node-strophe#1]
I have installed the node-strophe package within my NodeBB website. However I get an error '$ is not defined' even if I just include the following line of code : 
<code>var strophe = require("node-strophe");</code> 
OR 
<code>var strophe = require("node-strophe").Strophe;</code>

Can anyone help me resolve this issue ?

**Comment by tijszwinkels** [comment]
Hi Gauripadbidri,

_'$ is not defined'_ is usually caused by a missing jQuery include. However, I don't think that this error can be caused by node-strophe, as jQuery is not a dependency of node-strophe. Do you, by any chance, still get the error if you comment the whole _require("node-strophe");_. If so, the problem is elsewhere.

This is how we've included jQuery in one of our own node.js projects:

First install jquery and jsdom (needed to use jquery in node.js) as dependency from the command shell:

``` shell
npm install jquery --save
npm install "jsdom@~0.2.15" --save
```

Then, load the $ symbol in your .js:

``` js
$ = require('jquery')(require("jsdom").jsdom().parentWindow);
```

**Comment by gauripadbidri** [comment]
Thanks for your reply....I get this error, the moment I have the following line in my code..The moment this line is commented out, I o not see any errors and my site runs well : 

var strophe = require("node-strophe"); 
OR 
var strophe = require("node-strophe").Strophe;
