### ISSUE TITLE
node-strophe will not compile under V4 or V5

### ISSUE THREAD

**Issue by wyattbiker** [Iperity/node-strophe#2]
contextify is no longer a dependency in jsdom, because it's built in to node. Also and does not even compile nan (which contextify depends on) unless people have c++11.

I would appreciate it if you could update node-strophe package to use the latest jsdom? Thanks

**Comment by matthiasvdh** [comment]
Thanks for bringing this to our attention, Wyatt. We'll be looking into bringing node-strophe up to date.

If you get around to it before we do, PRs are of course welcome.

**Comment by wyattbiker** [comment]
Well i removed jsdom dependency and did manual install of jsdom of an older version which installed. 

BUT now I found out the newer version of strophe also uses websockets. Which is what my project really needs. I am kind of screwed because I did first version using just BOSH. And my boss is pissed off and wants me to use ughhhh Java.  Is there anything that can be done soon? I reviewed the strophe.js module and I am trying to understand what the requirements are to convert it to node, (comparing it to your old version). Any ideas, how I could do a quick convert for now. Thanks!

**Comment by matthiasvdh** [comment]
Glad you were able to get it to work on the old version. That is our current workaround as well.

At the moment we don't have anything to help you do a quick convert. When we do one ourselves, we will share it in the repo of course. So we'll keep this issue open, because you have a valid point.

Websockets and Java are truely out of scope for us. If you would like assistance with that, please find a commercial party that can help you out.

**Comment by wyattbiker** [comment]
Ok, thanks. 

Note:. visit https://github.com/strophe/strophejs/issues/167 for quick solution to use websockets.

**Comment by tijszwinkels** [comment]
The current master has been updated to work with Node.js 4+, and has been published to NPM. The version has been increased to 2.0.0, since this is an incompatible change; This version won't work on any Node.js that it was working on previously. The old version remains available for Node.js 0.x .

Please note that this is still the same old Strophe code.
